services:
  chat_history:
    build:
      context: './chathist'
      dockerfile: 'dockerfiles/chat_history.dockerfile'
    ports:
      - '8000'
    mem_limit: 10g
  chat_title:
    build:
      context: './chathist'
      dockerfile: 'dockerfiles/chat_title.dockerfile'
    ports:
      - '8001'

  # sculpgen:
  #   build:
  #     context: './sculpgen'
  #     dockerfile: 'sculpgen.dockerfile'
  #   ports:
  #     - '8001'

  server:
    build:
      context: './server'
      dockerfile: 'server.dockerfile'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
