services:
  chat_history:
    build:
      context: './chathist'
      dockerfile: 'dockerfiles/chat_history.dockerfile'

  # chat_title:
  #   build:
  #     context: './chathist'
  #     dockerfile: 'dockerfiles/chat_title.dockerfile'

  server:
    build:
      context: './server'
      dockerfile: 'server.dockerfile'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
