defaults:
  - _self_ # (Suppresses) UserWarning: In 'config': Defaults list is missing `_self_`.
  - experiments: exp1

config:
  ignore_index: -100
  endoftext: 50256
  gpt_flavor: 'gpt2-xl'
  model_name: 'gpt2-xl'
  model_path: '/Users/sameergururajmathad/Documents/CSC - 675/AI Capstone/chathist/models/pretrained'
  save_as: 'gpt2_history_finetuned'
  save_path: '/Users/sameergururajmathad/Documents/CSC - 675/AI Capstone/chathist/models/finetuned'

lora:
  use_lora: True
  alpha: 10
  rank: 10
