config:
  ignore_index: -100
  endoftext: 50256
  gpt_flavor: 'gpt2'
  model_name: 'gpt2'
  model_path: '/home/smathad/ai_capstone/chathist/models/pretrained'
  save_as: 'gpt2_chat_title_finetuned'
  save_path: '/home/smathad/ai_capstone/chathist/models/finetuned'

lora:
  use_lora: True
  alpha: 16
  rank: 16

train:
  learning_rate: 1e-5
  epochs: 3
  weight_decay: 0.1

data:
  batch_size: 16
  shuffle: True
  drop_last: True
  mask_input: True

style:
  style_name: 'phi3'
  prompt: ''
  input_query: "<|user|>\n"
  response_query: "\n<|llm|>\n"
  input_col: 'message'
  response_col: 'title'
  output_col: 'instruct'
  new_df: True
