config:
  ignore_index: -100
  endoftext: 50256
  gpt_flavor: 'gpt2'
  model_name: 'gpt2'
  model_path: '/home/smathad/ai_capstone/chathist/models/pretrained'
  save_as: 'gpt2_chat_title_finetuned'
  save_path: '/home/smathad/ai_capstone/chathist/models/finetuned'

lora:
  use_lora: False
  alpha: 16
  rank: 16

train:
  learning_rate: 1e-6
  epochs: 10