config:
  ignore_index: -100
  endoftext: 50256
  gpt_flavor: 'gpt2-xl'
  model_name: 'gpt2-xl'
  model_path: '/home/smathad/ai_capstone/chathist/models/pretrained'
  save_as: 'gpt2-xl_indian_history_finetuned'
  save_path: '/home/smathad/ai_capstone/chathist/models/finetuned'

data:
  batch_size: 16
  shuffle: True
  drop_last: True
  mask_input: True

lora:
  use_lora: True
  alpha: 16
  rank: 16

style:
  style_name: 'alpaca'
  prompt: '### You are an assistant with deep expertise in Indian history. You will answer any questions related to Indian history, providing accurate and insightful information.\n'
  input_query: "## Input:\n"
  response_query: "\n## Response:\n"
  input_col: 'instruction'
  response_col: 'response'
  output_col: 'instruct'
  new_df: True

train:
  learning_rate: 1e-5
  epochs: 3
  weight_decay: 0.1
