train:
  abstract_folder: '/home/smathad/ai_capstone/sculpgen/data/abstract' # Your style data folder path
  abstract_prefix: 'abstract_' # Prefix for the style images
  ext: '.jpg' # Extension of the style images
  sculpture_folder: '/home/smathad/ai_capstone/sculpgen/data/sculptures' # Your content data folder path
  sculpture_prefix: 'sculpture_' # Prefix for the content images
  epochs: 150 # Number of epochs to train
  learning_rate: 0.01 # Learning rate for the optimizer
  alpha: 1 # Weight for the content loss
  beta: 10000 # Weight for the style loss
  resize: 512 # Size to resize the images to
  images_per_content: 3 # Number of images to use for each content image
  save_prefix: 'sculpture_' # Prefix for the saved images
  save_path: '/home/smathad/ai_capstone/sculpgen/data/nst' # Path to save the generated images
  random_seed: 42 # Random seed for reproducibility
